fos_user_registration_register: 
    path: /
    defaults : { _controller :FOSUserBundle:Registration:register } 
    requirements: 
    methods: GET|POST 
    
fos_user_registration_check_email: 
    path: /check-email 
    defaults : { _controller :FOSUserBundle:Registration:checkEmail } 
    requirements: 
    methods: GET
    
fos_user_registration_confirm: 
    path: /confirm/{token} 
    defaults : { _controller :FOSUserBundle:Registration:confirm } 
    requirements: 
    methods: GET|POST
    
fos_user_registration_confirmed: 
    path: /confirmed 
    defaults : { _controller :FOSUserBundle:Registration:confirmed } 
    requirements: 
    methods: GET 