blog_homepage:
    path:     /
    defaults: { _controller: BlogBundle:Blog:index }
    
blog_new:
    path:     /new
    defaults: { _controller: BlogBundle:Blog:new }
    
blog_lecture:
    path:     /lecture
    defaults: { _controller: BlogBundle:Blog:lecture }
    
blog_profile:
    path:     /profile
    defaults: { _controller: BlogBundle:Blog:profile }
    
blog_delete:
    path:     /delete
    defaults: { _controller: BlogBundle:Blog:delete }
    
blog_edit:
    path:   /edit
    defaults: { _controller: BlogBundle:Blog:edit }
    